name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run npm install
        run: npm ci
      - name: Run npm build
        run: npm run build
      - name: Upload react build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: out
          if-no-files-found: error
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "No tests to run"
  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: out
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Copy Service Account credentials to JSON file
        run: echo "$GCP_SA_KEY" > "$GCP_SA_KEY_LOCATION"
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEYOND_REALITY_CONNECT }}
          GCP_SA_KEY_LOCATION: ${{ secrets.GCP_SA_KEY_LOCATION }}    
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY_LOCATION }} 
