name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run npm install
        run: npm ci
      - name: Run npm build
        run: npm run build
      - name: Upload react build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: out
          if-no-files-found: error
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "No tests to run"
  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: out
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        # 1. Create a new folder called app in the root of the project
        # 2. Create a file called google-services.json in the app folder
        # 3. Copy the contents of the service account key file into the google-services.json file
      - name: Create app folder
        run: mkdir app
      - name: Create google-services.json
        run: touch app/google-services.json
      - name: Copy service account key to google-services.json
        run: echo ${{ secrets.GCP_SA_KEY }} > app/google-services.json
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEYOND_REALITY_CONNECT }}
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: app/google-services.json
